AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Naming/PredicateMethod:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - a
    - b
    - id
    - to

Gemspec/DevelopmentDependencies:
  Enabled: false
